baseurl: "https://ningxinsu.github.io/"
languageCode: "en-us"
title: "Ningxin Su's Personal Website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "Personal Website for Ningxin Su"
  footer: "&copy; [Ningxin Su](https://ningxinsu.github.io) 2023 -- {Year} | [Github](https://github.com/NingxinSu) "

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
